user:
  outputs:
    development:
      type: bigquery
      method: service-account
      project: proud-climber-451915-f3  # Your GCP Project ID
      dataset: terra_kestra_bq_bucket  # Your staging dataset
      location: europe-west6           # The region of your dataset
      keyfile: '/Users/ignas/.gc/dbt-creds.json'
    production:
      type: bigquery
      method: service-account
      project: proud-climber-451915-f3  # Your GCP Project ID
      dataset: prod                    # Your production dataset
      location: europe-west6           # The region of your dataset
      keyfile: '/Users/ignas/.gc/dbt-creds.json'
      
    default:  # Optional fallback
      type: bigquery
      method: service-account
      project: proud-climber-451915-f3
      dataset: terra_kestra_bq_bucket
      location: europe-west6
      keyfile: /path/to/your/service-account-key.json
  target: development  # Set the default target to development
