default:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: proud-climber-451915-f3 # Your Google Cloud project ID
      dataset: terra_kestra_bq_bucket  # Your DEV dataset
      location: europe-west6
    prod:
      type: bigquery
      method: service-account
      project: proud-climber-451915-f3 # Your Google Cloud project ID
      dataset: prod  # Production dataset
      location: europe-west6
  target: dev